### ISSUE TITLE
Find novels

### ISSUE THREAD

**Issue by edponce** [edponce/DoyleInvestigators#1]
We can select ~5 novels, a couple related to Sherlock Holmes character and other novels, to allow intra- and inter- pattern comparisons.

**Comment by groppcw** [comment]
So, the adventures of Sherlock Holmes appears to be the only traditional crime novels written by Sir Arthur Conan Doyle, from my scanning of his works; he's written plenty of others, but they don't seem to fit the "unknown perpetrator amongst suspects" mold. However, even the Sherlock Holmes works have some nuance; in "The Valley of Fear", the supposed victim was actually the person who killed the dead body (an assassin), who was then dressed up to look like him to fake his own death, but the whole thing was orchestrated by Moriarty, who barely appears in the story. Assigning a character to "perpetrator" here involves some literary analysis; my suggestion would be that when it's unclear, to include all such candidates.

Below are the 4 Sherlock Holmes novels, which (more or less) follow the model of Sherlock Holmes and Watson following a trail of bodies to a bad guy, possibly with some ambiguity along the way as to who that bad guy is. 

* A Study in Scarlet - Note that the first part of the novel is the traditional crime story, with the second part being a backstory explaining the path that led to the inciting incident.
* The Sign of the Four
* The Hound of the Baskervilles
* The Valley of Fear

I can dig up some short stories to add to this, or I can provide some other novels he's written that follow the basic gist of "hero chases bad guy" but are not detective or crime novels. @edponce do you want to reach out to Edmon and ask what he'd prefer?

**Comment by edponce** [comment]
@groppcw Thanks for the thorough info. I will reach out to Edmon and see what he thinks, because the assignment states to use at least 5 novels.

**Comment by fabianfallasmoya** [comment]
According to Edmon's answer, we can work with novels and short stories.

@groppcw which novel I choose to start with?

**Comment by edponce** [comment]
@fabianfallasmoya I think it is safe to say that you can download the four Sherlock Holmes novels from project Gutenberg. Download them in text (UTF-8) format.
