### ISSUE TITLE
Create regex for sentence splitting

### ISSUE THREAD

**Issue by edponce** [edponce/DoyleInvestigators#10]
We need to come up with a regex for sentence splitting. Sentence splitting is a tricky one, given that some punctuation marks have more than one meaning (e.g., the period in Mr. Holmes). Also, these literary works have conversations (quoted text), so what do we consider as a sentence in these cases.
Example:
"Here I am!", said Sherlock.
Is this one or two sentences? I do not know but @fabianfallasmoya feel free to come up with consistent rules for the regex. I would consider it as a single sentence.
From my experience, I will state that do not expect the sentence segmentation to be perfect, something reasonable is good enough.

**Comment by fabianfallasmoya** [comment]
Eduardo, I created some drafts for this task:
`(([^\.\r\n;M!]+\n?)+(.")?(M[rR][sS]?\.\s)?(M)?)+`

This will split paragraph by ".", ";", "M", and "!". The reason for M is the "Mr." and "Mrs." cases. It is working well except in the cases where the "Mr." and "Mrs." are at the beginning of a paragraph.

For this reason, I created another regex considering that "Mr." and "Mrs." are at the beginning, this is the result:
`(([^\.\r\n;M!]+\n?)+(.")?(M[rR][sS]?\.\s)?(M)?)+|M[rR][sS]?\.\s([^\.;M!]+(.")?(M[rR][sS]?\.\s)?(M)?)+`

it does the job, but, it is pretty awful. Tomorrow we can talk! See you.

**Comment by edponce** [comment]
This is good, I will incorporate it into the sentence splitting placeholder. Thanks!
