### ISSUE TITLE
Create list of suspect-related words

### ISSUE THREAD

**Issue by edponce** [edponce/DoyleInvestigators#19]

**Comment by edponce** [comment]
dead, death, murder, crime, hurt, blood,  treasure, suffer, guilty, assassin, suspect, pain, vial

**Comment by fabianfallasmoya** [comment]
@edponce I was thinking about how to find negative words and I found this repository:

[https://github.com/jeffreybreen/twitter-sentiment-analysis-tutorial-201107/tree/08a269765a6b185d5f3dd522c876043ba9628715/data/opinion-lexicon-English](https://github.com/jeffreybreen/twitter-sentiment-analysis-tutorial-201107/tree/08a269765a6b185d5f3dd522c876043ba9628715/data/opinion-lexicon-English)

It is a .txt document. Do you think we can create a short method to take every single word from this list and perform a count from the corpus? In the end, we can keep (let's say) the top 15 of the most common negative words from a specific corpus.

What do you think?

**Comment by edponce** [comment]
We can definitely do a search and count this list of words as you recommend. Thanks!

In reality, we should not only use negative words but also words that are associated with the story, for example, if a crime was committed with a specific instrument, a festive day, etc. But this requires more knowledge of each story, so we can simply discuss this in the report.

**Comment by fabianfallasmoya** [comment]
Oh yes! you're right about the more tailored words from every novel.

I'll do this method from the GitHub I just mentioned. I will work on this method on Saturday!

**Comment by edponce** [comment]
@fabianfallasmoya FYI, I added a simple discussion of this idea to the report as well as the citation associated with the list of words.

**Comment by edponce** [comment]
I added to the Colab notebook code that makes a histogram from a given set of keywords. Extend this code to read the words from file and plot.

**Comment by fabianfallasmoya** [comment]
@edponce I went through all the code and realized that you made some changes to generalize the code.

From what I got, you created the methods **get_headings_map** and **get_rois** to use them instead of _get_chapters_, _get_parts_, etc.

Just for you to know: the methods: _get_chapters_, _get_parts_, etc., are not working (if you run the section Process Corpus you'll realize), there are missing old methods such as _get_gutenberg_chapter_labels_, _get_gutenberg_part_labels_, ...

In general, I liked the idea of having more generalizable methods. I found a little bug: in the case of 'The Valley of Fear' there is an epilogue, but when I run **roi_spans = get_rois(corpus_l, 'epilogue')** it returns a None. 

Now, I'll work on the negative words idea. Thanks for all the code, I have learned a lot.

**Comment by edponce** [comment]
Yes, I am reworking some code, the get_chapters, get_parts, etc (actually that entire code block) is deprecated. Process corpus was the driver using those functions so is also deprecated. I have never been fond of Jupyter Notebooks because all the code exists in one file. I prefer file encapsulation, but I have left that deprecated code as a note for me.

Apologies for not describing this in the code.

P.S. This way of writing the code, that is using functions only and passing corpus all the time, is not ideal. If this was a real project design this should have been written with object-oriented techniques.

**Comment by edponce** [comment]
@fabianfallasmoya Regarding the bug for **roi_spans = get_rois(corpus_l, 'epilogue')**, I fixed this. Copy the **get_headings_map** function from https://github.com/edponce/DoyleInvestigators/blob/develop/Project1_NLP.ipynb and add **import copy** to the notebook.

**Comment by fabianfallasmoya** [comment]
I just finished the implementation.

Just to compare>
This was your list: [dead, death, murder, crime, hurt, blood, treasure, suffer, guilty, assassin, suspect, pain, vial]
This is the list in the top 20 (for The Valley of Fear): 
[[('fear', 47) ('murder', 39) ('crime', 36) ('dead', 31) ('danger', 30) ('doubt', 27) ('dark', 24) ('strange', 22) ('hard', 22) ('bad', 19) ('trouble', 17) ('terrible', 15) ('cold', 15) ('struck', 14)  ('stranger', 14) ('death', 14) ('criminal', 14) ('worse', 13) ('dumb', 13) ('warning', 12)]]

The methods are in the section **Negative words frequency/histogram**. Now, I'll write all this in the overleaf.
