### ISSUE TITLE
Characterize novels

### ISSUE THREAD

**Issue by edponce** [edponce/DoyleInvestigators#2]
For each novel, we need to identify the following details:
* Plot summary
* What is the crime and its result?
* Who are the main characters?
* Who are the detectives?
* Who are the perpetrators?

**Comment by maofengggg** [comment]
Got it, I will do an example first and to see whether it is good.

**Comment by edponce** [comment]
FYI, from the Sherlock Holmes novels listed in https://github.com/edponce/DoyleInvestigators/issues/1#issuecomment-687407726, I will do "A Study in Scarlet".
