### ISSUE TITLE
Create Google Colaboratory project

### ISSUE THREAD

**Issue by edponce** [edponce/DoyleInvestigators#5]
Create Colab project and share with group.
Most likely we are going to only use spaCy and Python regex libraries.

**Comment by fabianfallasmoya** [comment]
I just created the colab space. This is my first time doing regex in a project (last time was when I worked as a web developer many years ago), so, today I spent many hours doing regex practice. I did that in another colab, so, the colab project will have only the project's code. Right now, I'll do a break and will continue today at 9 pm. I'll try to download something from Gutenberg and follow the tasks in the "Identify regex" issue.
