### ISSUE TITLE
Add literary context and structure discussion to document

### ISSUE THREAD

**Issue by groppcw** [edponce/DoyleInvestigators#7]
There are a lot of stories that we decided not to use because they don't fit the traditional mold; add discussion of this to the document.

"A Study in Scarlet" also is separated into two parts; the first is a more traditional crime story, and the second adds context to it. This makes it an interesting question; do we examine the first part as its own work, or the two parts together?

**Comment by edponce** [comment]
You mentioned that "A Study of Scarlet" Part 2 is a back-story, and that Part 1 can stand by itself as a standalone crime story.
We can consider Part 1 by itself, and consider Part2 -> Part1, and compare results.
