### ISSUE TITLE
Create regular expression for breaking paragraphs

### ISSUE THREAD

**Issue by edponce** [edponce/DoyleInvestigators#9]
Given that these are novels/stories where there are many conversations, it is not trivial to break the text into paragraphs.
The texts in Gutenberg Project do not contain text indentation as commonly used at the beginning of a paragraph, and contain multiple newlines between each person's conversation.

First we need to define what we consider as a paragraph. A simple rule is to consider text enclosed by multiple newlines as a paragraph. Note that many "paragraphs" will consist of a single line. It can be extended, by merging into a single paragraph all continuous conversations (text enclosed by quotation marks) as part of the most recent non-quoted text.

A more complex paragraph splitting is to consider the text context but that is out-of-scope because regular expressions are limited for context-based analysis.

**Comment by fabianfallasmoya** [comment]
@edponce I have a first approach for paragraph breaking. I followed your suggestion of considering continuous conversations as part of the same paragraph. Ideas I followed:

1. Text enclosed by multiple newlines is a paragraph.
2. One paragraph will merge with more paragraphs if the following paragraphs are part of the same conversation.
3. Also, I notice that some paragraph ended with ":", so, if a paragraph ends with ":", the following is considered as part of the same paragraph.

Thanks for the suggestions! I've spent a lot of time trying to run this **ROI** matching using findall, match, etc. I tried different things but in the end, nothing seemed to work properly. So, I ended up using the following code:

```python
def get_paragraphs(chapter_text):
    #get rid of '\r'
    chapter_text = re.sub(r'\r', "", chapter_text) 

    paragraphs = []
    while(len(chapter_text) > 1):
        #search first match of pattern
        match = re.search('[\d|"|\w](.+\n)+(.+:)\n+(.+\n?)+|[\d|"|\w](.+\n)+\n*("(.+\n)+\n+)*', chapter_text)
        
        #save result
        paragraphs.append(chapter_text[match.start():match.end()])

        #update text chapter
        chapter_text = chapter_text[match.end():len(chapter_text)]
    return paragraphs
```

Not sure if this is the best way (prob. not). But, at least I could try the regex I built and it is working. Tomorrow, I'll work on sentence breaking. I would appreciate any feedback.

BTW, here I'm not using global indexing... I hope this is not necessary!

**Comment by edponce** [comment]
@fabianfallasmoya The ideas you follow for paragraph splitting are good. I updated the paragraph regex and code to handle global index. By the way, I only compacted your regex, it was a very good starting point.
